apiVersion: v1
kind: Secret
metadata:
  name: groupsapp-secrets
  namespace: groupsapp
type: Opaque
data:
  DB_HOST: ZGF0YWJhc2UtMS5jNzhpeTZzMG1idTcudXMtZWFzdC0xLnJkcy5hbWF6b25hd3MuY29t
  DB_USER: YWRtaW4=
  DB_PASSWORD: dGVsZW1hdGljYTEyMw==
  DB_NAME: ZGF0YWJhc2UtMQ==
  JWT_SECRET: Y2hhdGFwcF9zZWNyZXRvX3N1cGVyX3NlZ3Vyb18yMDI0X2FiYzEyM3h5eg==
  AWS_ACCESS_KEY_ID: QVNJQVhZS0pWMzY1UEdIWk1MNVU=
  AWS_SECRET_ACCESS_KEY: K3dRZytFTnVQaHJzYmFpN2xhdTNHRkFVOHN6WW5nV3JBSUxPbGdmag==
  AWS_SESSION_TOKEN: SVFvSmIzSnBaMmx1WDJWakVHd2FDWFZ6TFhkbGMzUXRNaUpITUVVQ0lRRCtBdndkNklnelZWY3dpa2dQL1NrZmFhblpkQnkzWHQ4Ukp2dGZrNVBjd0FJZ2MrMGlIeHM3QmFDekxyenhHVjZLaVNiL2wyUUUwakJIM0w4cjNRbTVBU3dxdEFJSU5SQUFHZ3cxTXpNeU5qY3pOREV5TkRJaURBczdGZS9rNjVtbVNhYmp5eXFSQWkwdlhaellWaHM4NXhuZVE2Y3I4V3BteWZJandJNWdrUGUyYVRINml5VHA5dUlvc0dCSDU2b3dlRHREcEJoZDZnRGNXbUFaOXRRakcvRy9PbUYyNzcvN3ZzRlFKSWJaemdiVkwycUhwL0ZBa25EdlpIdzFTTGZmNUtiTXpQMXFHNVdsU0dWQjhjL2Ewc25tc3oxOUQ1VXhiRTdacEZNSmZCcHp1NEVVR0lxbXY2OGUwNHNzNG9COE1ydUdhOGQvSkZvSzJEbk1jRXFNMjFYRjB0cEhaTGlBZEpTVkdDZGNZMjVVcjJXVjVwUWpqSlhreVBZb2Q2c21oRmo0VE9ISWZKUUR4UTdkUDlkcG44ZmJaMzM4Sk9EUWtjL0hlVDg0bVpoWFlLU3U1WHdZNnlwZ2xXRUJtRG0xYW1peTQvQ01FaW1TTmRCNWlURUE4cFFUVHZOR1MwQ016K3dUS0lTdHluQW5RazNORWV3KzB6RFd5cDNQQmpxZEFkc3hkRVRPcWpRSURqSklKeERNa1FPTG9YN09pWW8yYWR4TE5FTERYeWZuRVBSdXprbUJTczNoRnhJbWtrYTNqVDYwalpzT0NRMW1TSWNYYmVzdEl0SGtndTFmZnpnYm03S25iODVTMGhwTUVJM1pOQ2MvNEk5WENRLzNwdzhkQTlNN3pRd21WWDYwSmZWWDBlSWZpNWp6aHYwc0lqTlNGNU96TmNPTXZqTUtlYnBmbGd5eStvZlplWGd3RExoMVNmWkJ5Q0dUTVhWQWhoMkhBajA5
  RABBITMQ_USER: Z3JvdXBzYXBw
  RABBITMQ_PASS: Z3JvdXBzYXBwMTIz
